### ISSUE TITLE
Security.wso2.com "default" not found when adding swagger definition through apictl

### ISSUE THREAD

**Issue by wx-yz** [wso2/k8s-api-operator#361]
**Description:**
Attaching the swagger definition I used here [swagger.yaml.txt](https://github.com/wso2/k8s-api-operator/files/4720153/swagger.yaml.txt). I got this swagger definition by,
1. Creating and publishing a simple API, just give a URL and create and publish with default /* resource
2. Use apictl to export the API definition
3. Unzip the file and get the swagger def

```
apictl add api -n MyRestAPI --from-file=swagger.yaml
```

Following can be seen in operator logs,

```
"level":"info","ts":1591139304.2786458,"logger":"controller_api","msg":"Reconciling API","Request.Namespace":"default","Request.Name":"myrestapi"}
{"level":"info","ts":1591139304.2787108,"logger":"controller_api","msg":"Controller Configurations","Request.Namespace":"default","Request.Name":"myrestapi","mgwToolkitImg":"wso2am/wso2micro-gw-toolkit:3.1.0","mgwRuntimeImg":"wso2/wso2micro-gw:3.1.0","kanikoImg":"gcr.io/kaniko-project/executor:v0.18.0","registryType":"DOCKER_HUB","repositoryName":"chintana","userNameSpace":"default","operatorMode":"default"}
{"level":"info","ts":1591139304.2806766,"logger":"controller_api","msg":"Swagger version 3.0.1"}
{"level":"info","ts":1591139304.2806873,"logger":"controller_api","msg":"Deployment mode is not set in the swagger."}
{"level":"info","ts":1591139304.2807016,"logger":"controller_api","msg":"getting security instance","Request.Namespace":"default","Request.Name":"myrestapi"}
{"level":"info","ts":1591139304.280705,"logger":"controller_api","msg":"API level security is defined"}
{"level":"info","ts":1591139304.2807312,"logger":"controller_api","msg":"Resource level security is defined"}
{"level":"info","ts":1591139304.2807424,"logger":"controller_api","msg":"defined security instance default is not found"}
{"level":"error","ts":1591139304.2807527,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"api-controller","request":"default/myrestapi","error":"Security.wso2.com \"default\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tapi-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tapi-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tapi-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tapi-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tapi-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\tapi-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

```

**Affected Product Version:**
k8s-api-operator-1.1.0

```
$ minikube version
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dinusha92** [comment]
Hi @wx-yz ,
This is an identified issue. Thank you for reporting this.
This happens due to an inconsisrency in default security policy name in API Manager and the API Operator.

API Operators default security is " default-security-jwt".
But in your swagger definition, the security is defined as "default".
API Operator tries to find the default security. Since it is not found, it gives the error.


Workaround:
1. Drop the security extension from swagger.yaml and try adding the API
2. Create a security custom resource with the name "default".

I'd prefer the 2nd approach as creating a security custom resource with "default" is a one time task.

You can find instructions on how to create security CR using the document below.

https://github.com/wso2/k8s-api-operator/blob/master/docs/HowToGuide/OverviewOfCrds/apply-security-to-api.md

Thanks.

**Comment by wx-yz** [comment]
Is it possible to mention this in our docs? In our operator README, if someone is following the steps, it does seem like it's possible to create a microgateway from any swagger definition.

Maybe it's a better approach to ignore the default security mechanism in swagger definition and add our own default-security-jwt at runtime. That to me seems to provide better user experience. Or link to a CRD with the default policy.

**Comment by pubudu538** [comment]
We have now added a document on setting this up -https://github.com/wso2/k8s-api-operator/tree/master/scenarios/scenario-21#deploy-an-api-gateway-in-ingressload-balancer-mode-and-publish-an-api-in-api-manager

Also, we have defined multiple JWT validations so that now we can now validate localhost with other hosts - https://github.com/wso2/k8s-api-operator/blob/master/api-operator/deploy/controller-configs/default_security_cr.yaml#L25
